# syntax = docker/dockerfile:1

ARG NODE_VERSION=20.6.1
FROM node:${NODE_VERSION}-slim as base

# Remix app lives here
WORKDIR /app

# Install pnpm
ARG PNPM_VERSION=8.15.5
RUN npm install -g pnpm@$PNPM_VERSION


# Throw-away build stage to reduce size of final image
FROM base as build

# Install packages needed to build node modules
RUN apt-get update -qq && \
    apt-get install -y build-essential pkg-config python-is-python3

# Install node modules
COPY --link package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod=false

# Copy application code
COPY --link . .

# Build application
RUN pnpm run build

# Final stage for app image
FROM base

# Copy built application
COPY --from=build /app /app

EXPOSE 5200
CMD [ "pnpm", "run", "start" ]
